# Generated by Django 6.0.6 on 2026-06-30 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence_file_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'در حال بررسی'), ('confirmed', 'تأیید شده'), ('dismissed', 'رد شده')], default='open', max_length=16)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to='accounts.telegramuser')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='accounts.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_reports_against', models.PositiveIntegerField(default=0)),
                ('confirmed_reports_against', models.PositiveIntegerField(default=0)),
                ('last_recalculated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to='accounts.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='TrustScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('verified', 'تأیید هویت'), ('positive_review', 'بازخورد مثبت دیگران'), ('successful_deal', 'معامله موفق'), ('report_received', 'ثبت گزارش تخلف علیه کاربر'), ('report_confirmed', 'تأیید گزارش تخلف توسط ادمین'), ('manual_admin', 'تنظیم دستی توسط ادمین')], max_length=32)),
                ('delta', models.IntegerField(help_text='Positive or negative point change')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='accounts.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
