# Generated by Django 6.0.6 on 2026-06-30 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('luggage', 'بار و چمدان')], default='luggage', max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('origin', models.CharField(blank=True, max_length=64)),
                ('destination', models.CharField(blank=True, max_length=64)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('available_weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار تأیید'), ('published', 'منتشر شده'), ('expired', 'منقضی شده'), ('rejected', 'رد شده')], default='pending_review', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='accounts.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
